import type { WeddingService, Profile } from '@/types/profile'
import type { User } from '@/types/user'

export const sampleWeddingServices: WeddingService[] = [
  {
    id: 'ws-1',
    category: 'venue',
    businessName: 'Royal Garden Banquet',
    contactPerson: 'Rajesh Kumar',
    mobile: '+91 98765 43210',
    email: 'royalgarden@example.com',
    address: '123 MG Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    description: 'Luxurious banquet hall with capacity for 500+ guests. Perfect for weddings and receptions.',
    priceRange: '₹2,00,000 - ₹5,00,000',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    consultationFee: 200,
    rating: 4.5,
    reviewCount: 45,
  },
  {
    id: 'ws-2',
    category: 'photographer',
    businessName: 'Moments Photography',
    contactPerson: 'Priya Sharma',
    mobile: '+91 98765 43211',
    email: 'moments@example.com',
    address: '456 Park Street',
    city: 'Delhi',
    state: 'Delhi',
    description: 'Professional wedding photography and videography services with modern equipment.',
    priceRange: '₹50,000 - ₹2,00,000',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    consultationFee: 200,
    rating: 4.8,
    reviewCount: 120,
  },
  {
    id: 'ws-3',
    category: 'caterer',
    businessName: 'Spice Garden Catering',
    contactPerson: 'Amit Patel',
    mobile: '+91 98765 43212',
    email: 'spicegarden@example.com',
    address: '789 Station Road',
    city: 'Ahmedabad',
    state: 'Gujarat',
    description: 'Multi-cuisine catering services specializing in vegetarian and Jain food.',
    priceRange: '₹500 - ₹1500 per plate',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    consultationFee: 200,
    rating: 4.6,
    reviewCount: 80,
  },
  {
    id: 'ws-4',
    category: 'decorator',
    businessName: 'Dream Decorations',
    contactPerson: 'Neha Singh',
    mobile: '+91 98765 43213',
    email: 'dreamdecor@example.com',
    address: '321 Mall Road',
    city: 'Jaipur',
    state: 'Rajasthan',
    description: 'Creative wedding decorations with traditional and modern themes.',
    priceRange: '₹1,00,000 - ₹5,00,000',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    consultationFee: 200,
    rating: 4.7,
    reviewCount: 65,
  },
  {
    id: 'ws-5',
    category: 'mehandi',
    businessName: 'Artistic Mehandi',
    contactPerson: 'Kavita Verma',
    mobile: '+91 98765 43214',
    email: 'artisticmehandi@example.com',
    address: '567 Gandhi Nagar',
    city: 'Pune',
    state: 'Maharashtra',
    description: 'Traditional and contemporary mehandi designs by experienced artists.',
    priceRange: '₹5,000 - ₹25,000',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    consultationFee: 200,
    rating: 4.9,
    reviewCount: 150,
  },
]

// Sample profiles removed - production environment uses Azure Cosmos DB only
export const sampleProfiles: Profile[] = []

// Sample users removed - production environment uses Azure Cosmos DB only
export const sampleUsers: User[] = []
