import type { WeddingService, Profile } from '@/types/profile'
import type { User } from '@/types/user'

export const sampleWeddingServices: WeddingService[] = [
  {
    id: 'ws-1',
    category: 'venue',
    businessName: 'Royal Garden Banquet',
    contactPerson: 'Rajesh Kumar',
    mobile: '+91 98765 43210',
    email: 'royalgarden@example.com',
    address: '123 MG Road',
    city: 'Mumbai',
    state: 'Maharashtra',
    description: 'Luxurious banquet hall with capacity for 500+ guests. Perfect for weddings and receptions.',
    priceRange: '₹2,00,000 - ₹5,00,000',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    consultationFee: 200,
    rating: 4.5,
    reviewCount: 45,
  },
  {
    id: 'ws-2',
    category: 'photographer',
    businessName: 'Moments Photography',
    contactPerson: 'Priya Sharma',
    mobile: '+91 98765 43211',
    email: 'moments@example.com',
    address: '456 Park Street',
    city: 'Delhi',
    state: 'Delhi',
    description: 'Professional wedding photography and videography services with modern equipment.',
    priceRange: '₹50,000 - ₹2,00,000',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    consultationFee: 200,
    rating: 4.8,
    reviewCount: 120,
  },
  {
    id: 'ws-3',
    category: 'caterer',
    businessName: 'Spice Garden Catering',
    contactPerson: 'Amit Patel',
    mobile: '+91 98765 43212',
    email: 'spicegarden@example.com',
    address: '789 Station Road',
    city: 'Ahmedabad',
    state: 'Gujarat',
    description: 'Multi-cuisine catering services specializing in vegetarian and Jain food.',
    priceRange: '₹500 - ₹1500 per plate',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    consultationFee: 200,
    rating: 4.6,
    reviewCount: 80,
  },
  {
    id: 'ws-4',
    category: 'decorator',
    businessName: 'Dream Decorations',
    contactPerson: 'Neha Singh',
    mobile: '+91 98765 43213',
    email: 'dreamdecor@example.com',
    address: '321 Mall Road',
    city: 'Jaipur',
    state: 'Rajasthan',
    description: 'Creative wedding decorations with traditional and modern themes.',
    priceRange: '₹1,00,000 - ₹5,00,000',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    consultationFee: 200,
    rating: 4.7,
    reviewCount: 65,
  },
  {
    id: 'ws-5',
    category: 'mehandi',
    businessName: 'Artistic Mehandi',
    contactPerson: 'Kavita Verma',
    mobile: '+91 98765 43214',
    email: 'artisticmehandi@example.com',
    address: '567 Gandhi Nagar',
    city: 'Pune',
    state: 'Maharashtra',
    description: 'Traditional and contemporary mehandi designs by experienced artists.',
    priceRange: '₹5,000 - ₹25,000',
    verificationStatus: 'verified',
    createdAt: new Date().toISOString(),
    consultationFee: 200,
    rating: 4.9,
    reviewCount: 150,
  },
]

export const sampleProfiles: Profile[] = [
  {
    id: 'profile-1',
    profileId: 'RS123497',
    firstName: 'Rahul',
    lastName: 'Sharma',
    fullName: 'Rahul Sharma',
    dateOfBirth: '1997-05-15',
    age: 27,
    gender: 'male',
    religion: 'Hindu',
    caste: 'Brahmin',
    community: 'North Indian',
    motherTongue: 'Hindi',
    education: 'B.Tech Computer Science',
    occupation: 'Software Engineer',
    salary: '₹12-15 LPA',
    location: 'Bangalore',
    country: 'India',
    maritalStatus: 'never-married',
    email: 'rahul@example.com',
    mobile: '+91 98765 11111',
    hideEmail: false,
    hideMobile: false,
    photos: [],
    bio: 'Looking for a life partner who shares similar values and interests.',
    height: '5\'10"',
    familyDetails: 'Father: Business, Mother: Homemaker, 1 younger sister',
    dietPreference: 'veg',
    drinkingHabit: 'never',
    smokingHabit: 'never',
    status: 'verified',
    trustLevel: 5,
    createdAt: new Date().toISOString(),
    emailVerified: true,
    mobileVerified: true,
    isBlocked: false,
    membershipPlan: 'free',
  },
  {
    id: 'profile-2',
    profileId: 'PG234598',
    firstName: 'Priya',
    lastName: 'Gupta',
    fullName: 'Priya Gupta',
    dateOfBirth: '1998-08-22',
    age: 26,
    gender: 'female',
    religion: 'Hindu',
    caste: 'Vaishya',
    community: 'North Indian',
    motherTongue: 'Hindi',
    education: 'MBA Finance',
    occupation: 'Financial Analyst',
    salary: '₹8-10 LPA',
    location: 'Mumbai',
    country: 'India',
    maritalStatus: 'never-married',
    email: 'priya@example.com',
    mobile: '+91 98765 22222',
    hideEmail: false,
    hideMobile: false,
    photos: [],
    bio: 'Family-oriented person seeking a well-educated and caring partner.',
    height: '5\'5"',
    familyDetails: 'Father: Doctor, Mother: Teacher, 1 elder brother',
    dietPreference: 'veg',
    manglik: false,
    drinkingHabit: 'never',
    smokingHabit: 'never',
    status: 'verified',
    trustLevel: 5,
    createdAt: new Date().toISOString(),
    emailVerified: true,
    mobileVerified: true,
    isBlocked: false,
    membershipPlan: '6-month',
  },
  {
    id: 'profile-3',
    profileId: 'AK345699',
    firstName: 'Amit',
    lastName: 'Kumar',
    fullName: 'Amit Kumar',
    dateOfBirth: '1999-03-10',
    age: 25,
    gender: 'male',
    religion: 'Hindu',
    caste: 'Kshatriya',
    community: 'North Indian',
    motherTongue: 'Hindi',
    education: 'CA',
    occupation: 'Chartered Accountant',
    salary: '₹10-12 LPA',
    location: 'Delhi',
    country: 'India',
    maritalStatus: 'never-married',
    email: 'amit@example.com',
    mobile: '+91 98765 33333',
    hideEmail: false,
    hideMobile: false,
    photos: [],
    bio: 'Traditional values with modern outlook. Looking for understanding life partner.',
    height: '5\'8"',
    familyDetails: 'Father: Retired Government Officer, Mother: Homemaker',
    dietPreference: 'veg',
    manglik: false,
    drinkingHabit: 'occasionally',
    smokingHabit: 'never',
    status: 'verified',
    trustLevel: 3,
    createdAt: new Date().toISOString(),
    emailVerified: true,
    mobileVerified: true,
    isBlocked: false,
    membershipPlan: '1-year',
  },
  {
    id: 'profile-free',
    profileId: 'FP999999',
    firstName: 'Test',
    lastName: 'FreePlan',
    fullName: 'Test FreePlan',
    dateOfBirth: '1996-01-15',
    age: 28,
    gender: 'male',
    religion: 'Hindu',
    caste: 'General',
    community: 'North Indian',
    motherTongue: 'Hindi',
    education: 'B.Com',
    occupation: 'Business',
    salary: '₹5-8 LPA',
    location: 'Delhi',
    country: 'India',
    maritalStatus: 'never-married',
    email: 'freeuser@example.com',
    mobile: '+91 98765 99999',
    hideEmail: false,
    hideMobile: false,
    photos: [],
    bio: 'Free plan test user for testing blur functionality.',
    height: '5\'8"',
    familyDetails: 'Test family',
    dietPreference: 'veg',
    drinkingHabit: 'never',
    smokingHabit: 'never',
    status: 'verified',
    trustLevel: 1,
    createdAt: new Date().toISOString(),
    emailVerified: true,
    mobileVerified: true,
    isBlocked: false,
    membershipPlan: 'free',
  },
]

export const sampleUsers: User[] = [
  {
    userId: 'USER001',
    password: 'pass123',
    profileId: 'profile-1',
    createdAt: new Date().toISOString(),
  },
  {
    userId: 'USER002',
    password: 'pass456',
    profileId: 'profile-2',
    createdAt: new Date().toISOString(),
  },
  {
    userId: 'USER003',
    password: 'pass789',
    profileId: 'profile-3',
    createdAt: new Date().toISOString(),
  },
  {
    userId: 'FREEUSER',
    password: 'free123',
    profileId: 'profile-free',
    createdAt: new Date().toISOString(),
  },
]
